### ISSUE TITLE
Heatstack deletion error

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#65]
Cannot delete lasair-dev stack.

```
2022-12-02 16:34:05.196 22 INFO heat.engine.resource [req-01f6df83-803a-41eb-bca4-d1f7687169e2 royw Lasair - default default] DELETE: TemplateResource "0" [fce8d330-c460-4d93-88c8-e3e9b87d6b2a] Stack "lasair-dev-filter_group-wfhc5mvvwj4h" [b0622757-9f5d-45be-8664-d52e7c320d8b]
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource Traceback (most recent call last):
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource   File "/var/lib/kolla/venv/lib/python3.6/site-packages/heat/engine/resource.py", line 916, in _action_recorder
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource     yield
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource   File "/var/lib/kolla/venv/lib/python3.6/site-packages/heat/engine/resource.py", line 2040, in delete
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource     *action_args)
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource   File "/var/lib/kolla/venv/lib/python3.6/site-packages/heat/engine/resource.py", line 978, in action_handler_task
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource     done = check(handler_data)
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource   File "/var/lib/kolla/venv/lib/python3.6/site-packages/heat/engine/resources/stack_resource.py", line 608, in check_delete_complete
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource     return self._check_status_complete(self.DELETE)
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource   File "/var/lib/kolla/venv/lib/python3.6/site-packages/heat/engine/resources/stack_resource.py", line 451, in _check_status_complete
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource     action=action)
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource heat.common.exception.ResourceFailure: resources[0]: Stack DELETE cancelled
2022-12-02 16:34:05.196 22 ERROR heat.engine.resource
```

**Comment by GregBlow** [comment]
```
(openstack-config) [stack@sv-admin-0 openstack-config]$ openstack stack resource list 4e67acab-e55b-4a48-859d-7aa2138ef072
+---------------------------+--------------------------------------+-----------------------------------------------------------+--------------------+----------------------+
| resource_name             | physical_resource_id                 | resource_type                                             | resource_status    | updated_time         |
+---------------------------+--------------------------------------+-----------------------------------------------------------+--------------------+----------------------+
| cassandra_group           | 8494ccbe-4458-4f82-9222-8dde71537b9f | OS::Heat::ResourceGroup                                   | DELETE_IN_PROGRESS | 2022-12-02T15:46:27Z |
| cassandra_server_group    | 4befcade-ed21-4164-a2ad-59139b4c35cb | OS::Nova::ServerGroup                                     | CREATE_COMPLETE    | 2022-12-02T15:46:27Z |
| backend_db_group          | 58974bf5-1687-473f-af90-0b45a20dcd5e | OS::Heat::ResourceGroup                                   | DELETE_COMPLETE    | 2022-12-02T15:46:27Z |
| db_server_group           | 9732f7a9-745b-4206-8f80-6f15b4e303aa | OS::Nova::ServerGroup                                     | DELETE_COMPLETE    | 2022-12-02T15:46:27Z |
| kafka_pub                 | 70fe746a-bd66-4401-9aa3-015778064432 | file:///home/ubuntu/lasair-deploy/server_with_volume.yaml | DELETE_COMPLETE    | 2022-12-02T15:46:27Z |
| parallel_ssh_group        | aaba7eb7-f84a-4a3e-af61-ca269947c3e0 | OS::Heat::ResourceGroup                                   | DELETE_COMPLETE    | 2022-12-02T15:46:27Z |
| parallel_ssh_server_group | 8f237c4e-3bab-4f84-94bc-a83e2fb1ca74 | OS::Nova::ServerGroup                                     | DELETE_COMPLETE    | 2022-12-02T15:46:27Z |
| svc                       | a5983839-7e0b-480d-923f-77a928a9ae5f | file:///home/ubuntu/lasair-deploy/server_with_volume.yaml | DELETE_COMPLETE    | 2022-12-02T15:46:27Z |
| ingest_group              | 6c75d488-48cd-4fb3-a8ed-504b20fcd706 | OS::Heat::ResourceGroup                                   | DELETE_IN_PROGRESS | 2022-12-02T15:46:27Z |
| ingest_server_group       | 13c95a0f-8f76-4496-8e7c-2dd5861c248b | OS::Nova::ServerGroup                                     | CREATE_COMPLETE    | 2022-12-02T15:46:27Z |
| share_fs                  | 74571601-e781-4dd7-8f8f-38ddcefdf63d | OS::Manila::Share                                         | DELETE_COMPLETE    | 2022-12-02T15:46:28Z |
| db                        | 7199bf0f-f79a-4d9e-bc2c-3fb6926d67ef | file:///home/ubuntu/lasair-deploy/server_with_volume.yaml | DELETE_IN_PROGRESS | 2022-12-02T15:46:28Z |
| sherlock_group            | acf6bca9-6864-4d3a-881b-915988806412 | OS::Heat::ResourceGroup                                   | DELETE_IN_PROGRESS | 2022-12-02T15:46:28Z |
| sherlock_server_group     | 410cc6e4-2955-4d84-ac9c-e1dbf6ec9484 | OS::Nova::ServerGroup                                     | CREATE_COMPLETE    | 2022-12-02T15:46:28Z |
| filter_group              | b0622757-9f5d-45be-8664-d52e7c320d8b | OS::Heat::ResourceGroup                                   | DELETE_IN_PROGRESS | 2022-12-02T15:46:28Z |
| filter_server_group       | 37207014-113c-424d-93f2-5e9c89284519 | OS::Nova::ServerGroup                                     | CREATE_COMPLETE    | 2022-12-02T15:46:28Z |
| frontend_db_group         | d344ef79-a0e9-4f5b-9043-57e8c562ce53 | OS::Heat::ResourceGroup                                   | DELETE_COMPLETE    | 2022-12-02T15:46:28Z |
| kafka_group               | 6c1d8c67-8176-4233-9686-c3daae99fb7a | OS::Heat::ResourceGroup                                   | DELETE_COMPLETE    | 2022-12-02T15:46:28Z |
| kafka_server_group        | d54a6fa1-e0dd-4bf1-9469-40f3c48b915f | OS::Nova::ServerGroup                                     | DELETE_COMPLETE    | 2022-12-02T15:46:28Z |
| web                       | 69343aae-e14b-41d3-8c07-84ffe5275eda | file:///home/ubuntu/lasair-deploy/server_with_volume.yaml | DELETE_COMPLETE    | 2022-12-02T15:46:28Z |
| default_server_group      | 3c7618ea-53ea-4cad-87f3-f3634aee002b | OS::Nova::ServerGroup                                     | CREATE_COMPLETE    | 2022-12-02T15:46:28Z |
+---------------------------+--------------------------------------+-----------------------------------------------------------+--------------------+----------------------+
```

**Comment by GregBlow** [comment]
https://platform9.com/kb/openstack/unable-to-delete-stacks-stuck-in-delete_failed-state

**Comment by GregBlow** [comment]
no progress so far. Running a check on the stack and then trying to delete has however produced a different pattern of log output.

**Comment by GregBlow** [comment]
```
2022-12-02 16:56:05.203 21 INFO heat.engine.stack [req-58d03f05-b67e-421f-96bb-b5831cc66eb7 admin admin - default default] Triggering resource 27769 for cleanup
2022-12-02 17:11:54.526 22 INFO heat.engine.check_resource [req-58d03f05-b67e-421f-96bb-b5831cc66eb7 admin admin - default default] Re-trigger resource: ConvergenceNode(rsrc_id=27640, is_update=False)
2022-12-02 17:11:54.760 24 INFO heat.engine.check_resource [req-58d03f05-b67e-421f-96bb-b5831cc66eb7 admin admin - default default] Re-trigger resource: ConvergenceNode(rsrc_id=27658, is_update=False)
2022-12-02 17:11:59.249 21 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] deleting ResourceGroup "cassandra_group" [8494ccbe-4458-4f82-9222-8dde71537b9f] Stack "lasair-dev" [4e67acab-e55b-4a48-859d-7aa2138ef072]
2022-12-02 17:11:59.307 21 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] delete ResourceGroup "cassandra_group" [8494ccbe-4458-4f82-9222-8dde71537b9f] Stack "lasair-dev" [4e67acab-e55b-4a48-859d-7aa2138ef072] attempt 1
2022-12-02 17:12:01.325 21 INFO heat.engine.service [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Deleting stack lasair-dev-db-o32hypxanhif
2022-12-02 17:12:01.358 21 INFO heat.engine.stack [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Stack DELETE FAILED (lasair-dev-db-o32hypxanhif): Stack DELETE cancelled
2022-12-02 17:12:02.261 24 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] deleting ResourceGroup "ingest_group" [6c75d488-48cd-4fb3-a8ed-504b20fcd706] Stack "lasair-dev" [4e67acab-e55b-4a48-859d-7aa2138ef072]
2022-12-02 17:12:02.324 24 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] delete ResourceGroup "ingest_group" [6c75d488-48cd-4fb3-a8ed-504b20fcd706] Stack "lasair-dev" [4e67acab-e55b-4a48-859d-7aa2138ef072] attempt 1
2022-12-02 17:12:02.819 23 INFO heat.engine.check_resource [req-58d03f05-b67e-421f-96bb-b5831cc66eb7 admin admin - default default] Re-trigger resource: ConvergenceNode(rsrc_id=27688, is_update=False)
2022-12-02 17:12:05.368 20 INFO heat.engine.check_resource [req-58d03f05-b67e-421f-96bb-b5831cc66eb7 admin admin - default default] Re-trigger resource: ConvergenceNode(rsrc_id=27718, is_update=False)
2022-12-02 17:12:05.682 22 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] deleting TemplateResource "0" [fce8d330-c460-4d93-88c8-e3e9b87d6b2a] Stack "lasair-dev-filter_group-wfhc5mvvwj4h" [b0622757-9f5d-45be-8664-d52e7c320d8b]
2022-12-02 17:12:05.721 22 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] delete TemplateResource "0" [fce8d330-c460-4d93-88c8-e3e9b87d6b2a] Stack "lasair-dev-filter_group-wfhc5mvvwj4h" [b0622757-9f5d-45be-8664-d52e7c320d8b] attempt 1
2022-12-02 17:12:05.734 22 INFO heat.engine.service [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Deleting stack lasair-dev-filter_group-wfhc5mvvwj4h-0-xj46ktgkfsbq
2022-12-02 17:12:06.538 21 INFO heat.engine.worker [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] [lasair-dev-db-o32hypxanhif(7199bf0f-f79a-4d9e-bc2c-3fb6926d67ef)] Stopped all active workers for stack DELETE
2022-12-02 17:12:06.611 21 INFO heat.engine.stack [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Triggering resource 27769 for cleanup
2022-12-02 17:12:06.642 23 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] deleting Server "srv" [c23e847a-3607-4dc6-b2f5-da9e6cc15b2b] Stack "lasair-dev-db-o32hypxanhif" [7199bf0f-f79a-4d9e-bc2c-3fb6926d67ef]
2022-12-02 17:12:06.686 23 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] delete Server "srv" [c23e847a-3607-4dc6-b2f5-da9e6cc15b2b] Stack "lasair-dev-db-o32hypxanhif" [7199bf0f-f79a-4d9e-bc2c-3fb6926d67ef] attempt 1
2022-12-02 17:12:07.733 20 INFO heat.engine.service [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Deleting stack lasair-dev-ingest_group-3s7bb7bdpf3x-0-xmhmy5f5ehxu
2022-12-02 17:12:10.094 20 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] deleting Server "srv" [fb88d178-702b-4226-b803-74fbc5998d87] Stack "lasair-dev-cassandra_group-7dgfki2wbabz-0-u6kdt4o3lhux" [789ffb45-5fa5-4e11-b465-0dc6f9037cde]
2022-12-02 17:12:10.127 20 INFO heat.engine.resource [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] delete Server "srv" [fb88d178-702b-4226-b803-74fbc5998d87] Stack "lasair-dev-cassandra_group-7dgfki2wbabz-0-u6kdt4o3lhux" [789ffb45-5fa5-4e11-b465-0dc6f9037cde] attempt 1
2022-12-02 17:12:10.847 22 INFO heat.engine.worker [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] [lasair-dev-filter_group-wfhc5mvvwj4h-0-xj46ktgkfsbq(fce8d330-c460-4d93-88c8-e3e9b87d6b2a)] Stopped all active workers for stack DELETE
2022-12-02 17:12:10.955 22 INFO heat.engine.stack [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Triggering resource 27682 for cleanup
2022-12-02 17:12:12.831 20 INFO heat.engine.worker [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] [lasair-dev-ingest_group-3s7bb7bdpf3x-0-xmhmy5f5ehxu(e1397047-a6b2-410e-a25b-2e64703b0594)] Stopped all active workers for stack DELETE
2022-12-02 17:12:12.899 20 INFO heat.engine.stack [req-b0a405b0-2fb8-45aa-982a-e326a0a55493 admin admin - default default] Triggering resource 27691 for cleanup
```

**Comment by GregBlow** [comment]
setting sv-sm* offline has allowed lasiar-dev-sherlock-0 delete command to complete successfully.

**Comment by astrodb** [comment]
@gpfrancis checking on setting AZ in heat and will test to confirm whether the problem is down to sm nodes

**Comment by tms-epcc** [comment]
GarethTest failedd

**Comment by GregBlow** [comment]
At present no known issues deleting heat stacks. In addition to deployment to supermicro nodes causing issue, was related to https://github.com/lsst-uk/somerville-operations/issues/66.
